### ISSUE TITLE
Timeline for code release!

### ISSUE THREAD

**Issue by zachytong** [DLUT-LYZ/CODA-LM#1]
Dear author,

Thanks for this great work! I want to know is there any estimated timeline for your open-source plan? 

Best wish!

**Comment by KaiChen1998** [comment]
Thank you for your interest in our work! We have released a mini-set with the dataloader script for demonstration usage, while the full CODA-LM dataset will be utilized to hold to ECCV24 Workshop on Multimodal Perception and Comprehension of Corner Cases in Autonomous Driving. You might check the timeline and latest updates in our official workshop [website](https://coda-dataset.github.io/w-coda2024/)!
