### ISSUE TITLE
dataset link

### ISSUE THREAD

**Issue by GallonDeng** [DLUT-LYZ/CODA-LM#2]
nice work! where is the dataset link?

**Comment by KaiChen1998** [comment]
Thank you for your interest in our work! We have released a mini-set with the dataloader script for demonstration usage, while the full CODA-LM dataset will be utilized to hold to ECCV24 Workshop on Multimodal Perception and Comprehension of Corner Cases in Autonomous Driving. You might check the timeline and latest updates in our official workshop [website](https://coda-dataset.github.io/w-coda2024/)!

**Comment by GallonDeng** [comment]
@KaiChen1998 the dataset will be released on June 15, 2024?
