### ISSUE TITLE
about labeling tool

### ISSUE THREAD

**Issue by GallonDeng** [DLUT-LYZ/CODA-LM#3]
it is time consuming to annotate the coda-lm dataset. In the  paper, a labeling tool is mentioned. Will it be open for annotating more other datasets?

**Comment by DLUT-LYZ** [comment]
Thank you for your interest in our work! We have released the labeling tool code.

**Comment by KaiChen1998** [comment]
> Thank you for your interest in our work! We have released the labeling tool code.

@AllenDun You might check the readme file [here](https://github.com/DLUT-LYZ/CODA-LM/tree/main/labeling) for detailed usage.
