### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by Zoeeeing** [DLUT-LYZ/CODA-LM#5]
Dear author, 
Thanks for your great work! Will the evaluation code be made available? We can use it for offline evaluation.
Best

**Comment by KaiChen1998** [comment]
@Zoeeeing Thank you for your interest in our CODA-LM! Although we cannot release the ground truth annotations of the CODA-LM Test set, we release the [evaluation code](https://github.com/DLUT-LYZ/CODA-LM/tree/main/evaluation) for evaluation on the CODA-LM val set. 

Moreover, CODA-LM is now utilized to hold the [W-CODA](https://coda-dataset.github.io/w-coda2024/track1/index.html) challenge in ECCV 2024. Welcome to submit your results for our competition!
