### ISSUE TITLE
CODA-LM Test set

### ISSUE THREAD

**Issue by EMZucas** [DLUT-LYZ/CODA-LM#6]
Dear author,
May I ask if it is possible to publish the true annotations of the test set as soon as possible?

**Comment by KaiChen1998** [comment]
CODA-LM is now utilized to hold our ECCV24 W-CODA challenges, and we will only consider releasing the GT annotations of CODA-LM after the end of ECCV 2024. Archive our [website](https://coda-dataset.github.io/w-coda2024/track1/) and stay tuned!
