### ISSUE TITLE
test set annotations

### ISSUE THREAD

**Issue by Zoeeeing** [DLUT-LYZ/CODA-LM#9]
Dear author, when will the test set annotations be released, as we want to evaluate the performance in CODA-LM?

**Comment by KaiChen1998** [comment]
@Zoeeeing Thanks for your patience! We are glad to announce that the annotations of CODA-LM Test set have been released in [HuggingFace](https://huggingface.co/datasets/KaiChen1998/coda-lm/tree/main/CODA-LM/Test)!

Welcome to check!
